version: "3.9"
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node

  node:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    restart: "always"
    volumes:
      - ./backend:/src/app
      - /src/app/node_modules
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
