version: "3.9"
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node

  node:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    restart: "always"
    volumes:
      - ./backend:/src/app
      - /src/app/node_modules
    ports:
      - 3000:3000
    logging:
      driver: json-file
    deploy:
      labels:
        swarm.autoscaler: 'true'
        swarm.autoscaler.maximum: '5'
        swarm.autoscaler.minimum: '3'
